local state = {
    WAIT = "WAIT",

    GET_COUNT_OF_RECEIVED_SMS = {
        WAITING_CMGF_OK = "SMS_COUNT_WAITING_CMGF_OK",
        WAITING_CPMS_RESULT = "SMS_COUNT_WAITING_CPMS_RESULT",
    },

    READ_SMS_BY_INDEX = {
        WAITING_CMGF_OK = "READ_SMS_WAITING_CMGF_OK",
        WAITING_CMGR_RESULT = "READ_SMS_WAITING_CMGR_RESULT",
    }
}

return state