local state = {
    WAIT = "WAIT",

    SEND_SMS = {
        WAITING_CMGF_OK = "SEND_SMS_WAITING_CMGF_OK",
        WAITING_CMGS_OK = "SEND_SMS_WAITING_CMGS_OK",
        WAITING_PDU_TEXT_OK = "SEND_SMS_WAITING_PDU_TEXT_OK",
    },

    GET_COUNT_OF_RECEIVED_SMS = {
        WAITING_CMGF_OK = "SMS_COUNT_WAITING_CMGF_OK",
        WAITING_CPMS_RESULT = "SMS_COUNT_WAITING_CPMS_RESULT",
    },

    READ_SMS_BY_INDEX = {
        WAITING_CMGF_OK = "READ_SMS_WAITING_CMGF_OK",
        WAITING_CMGR_RESULT = "READ_SMS_WAITING_CMGR_RESULT",
    },

    READ_ALL_SMS = {
        WAITING_CMGF_OK = "READ_ALL_SMS_WAITING_CMGF_OK",
        WAITING_CMGL_RESULT = "READ_ALL_SMS_WAITING_CMGL_RESULT",
    }
}

return state